# Generated by Django 3.0.4 on 2020-03-29 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('updated', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('country_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('country_ID', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('flag_image', models.CharField(max_length=100)),
                ('iso3', models.CharField(max_length=100)),
                ('cases', models.IntegerField()),
                ('today_cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('today_deaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('active', models.IntegerField()),
                ('critical', models.IntegerField()),
                ('cases_per_million', models.IntegerField()),
                ('deaths_per_million', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cases', models.IntegerField()),
                ('today_cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('active', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='county',
            fields=[
                ('county_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('updated', models.CharField(max_length=100)),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.state')),
            ],
        ),
    ]
