# Generated by Django 3.0.4 on 2020-03-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20200328_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='updated',
            field=models.CharField(max_length=100),
        ),
    ]
